# Generated by Django 5.0.7 on 2024-07-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrow", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="borrow_date",
            field=models.DateField(editable=False),
        ),
    ]
